#!/bin/bash

ARID_HOME="$HOME/.arid"

ARID_FILE_ALIASES=".vimrc .ackrc .gemrc .gitignore .gitconfig .irbrc .pryrc .tmux.conf"
ARID_DIRECTORY_ALIASES=".vim .config"

echo "== Installing Arid dotfiles"

for x in $(echo $ARID_FILE_ALIASES); do \
  if [ -h $HOME/$x ]
  then
    echo " * $x is already symlinked."
    continue
  fi

  if [ -f $HOME/$x ]
  then
    echo -n " * Backing up $x..."
    mv $HOME/$x $HOME/$x.old
    echo "Done."
  fi
  echo -n " * Symlinking $HOME/$x..."
  ln -sf $ARID_HOME/$x $HOME/$x
  echo "Done."
done


for x in $(echo $ARID_DIRECTORY_ALIASES); do \
  if [ -h $HOME/$x ]
  then
    echo " * $x is already symlinked."
    continue
  fi

  if [ -d $HOME/$x ]
  then
    echo -n "Backing up $x..."
    mv $HOME/$x $HOME/$x.old
    echo "Done."
  fi
  echo -n " * Symlinking $HOME/$x..."
  ln -sf $ARID_HOME/$x $HOME/$x
  echo "Done."
done

echo "== Done!"
